spring:
  application:
    name: cosbell-spa
  datasource:
    url: jdbc:postgresql://localhost:5432/cosbell.spa
    username: postgres
    password: tu_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
