server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: TU_CORREO@gmail.com
    password: TU_CONTRASEÑA
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://ep-round-silence-a8f18yh7-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_fFKXsP16ANZc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
